In [1]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.13/dist-packages (4.8.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets) (4.2.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.1.3)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from datasets) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.13/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from datasets) (4.0.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.12.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (1.33.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from datasets) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.14.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.7.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2026.5)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<8.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (7.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.25.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.25.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [2]:
from datasets import load_dataset

In [3]:
edacc = load_dataset(
    "edinburghcstr/edacc"
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/6.95k [00:00<?, ?B/s]

data/validation-00000-of-00006-17ec18f4d(…): reconstructing file:   0%|          |  0.00B /  457MB

data/validation-00000-of-00006-17ec18f4d(…): downloading bytes:           |  0.00B

data/validation-00001-of-00006-6f3978e4f(…): reconstructing file:   0%|          |  0.00B /  478MB

data/validation-00001-of-00006-6f3978e4f(…): downloading bytes:           |  0.00B

data/validation-00002-of-00006-5a1d86079(…): reconstructing file:   0%|          |  0.00B /  446MB

data/validation-00002-of-00006-5a1d86079(…): downloading bytes:           |  0.00B

data/validation-00003-of-00006-b26008b09(…): reconstructing file:   0%|          |  0.00B /  492MB

data/validation-00003-of-00006-b26008b09(…): downloading bytes:           |  0.00B

data/validation-00004-of-00006-8cad96ca1(…): reconstructing file:   0%|          |  0.00B /  787MB

data/validation-00004-of-00006-8cad96ca1(…): downloading bytes:           |  0.00B

data/validation-00005-of-00006-976f2f011(…): reconstructing file:   0%|          |  0.00B /  676MB

data/validation-00005-of-00006-976f2f011(…): downloading bytes:           |  0.00B

data/test-00000-of-00010-f0aceb1ca4406ff(…): reconstructing file:   0%|          |  0.00B /  471MB

data/test-00000-of-00010-f0aceb1ca4406ff(…): downloading bytes:           |  0.00B

data/test-00001-of-00010-856b016d9d438ff(…): reconstructing file:   0%|          |  0.00B /  274MB

data/test-00001-of-00010-856b016d9d438ff(…): downloading bytes:           |  0.00B

data/test-00002-of-00010-2b021baedb4deb8(…): reconstructing file:   0%|          |  0.00B /  333MB

data/test-00002-of-00010-2b021baedb4deb8(…): downloading bytes:           |  0.00B

data/test-00003-of-00010-4de275e704375a0(…): reconstructing file:   0%|          |  0.00B /  498MB

data/test-00003-of-00010-4de275e704375a0(…): downloading bytes:           |  0.00B

data/test-00004-of-00010-806407c9bc68112(…): reconstructing file:   0%|          |  0.00B /  257MB

data/test-00004-of-00010-806407c9bc68112(…): downloading bytes:           |  0.00B

data/test-00005-of-00010-9c97c4c4c8d01f8(…): reconstructing file:   0%|          |  0.00B /  282MB

data/test-00005-of-00010-9c97c4c4c8d01f8(…): downloading bytes:           |  0.00B

data/test-00006-of-00010-cc4648d0f66f65a(…): reconstructing file:   0%|          |  0.00B /  354MB

data/test-00006-of-00010-cc4648d0f66f65a(…): downloading bytes:           |  0.00B

data/test-00007-of-00010-ea5ed4464ecff3c(…): reconstructing file:   0%|          |  0.00B /  439MB

data/test-00007-of-00010-ea5ed4464ecff3c(…): downloading bytes:           |  0.00B

data/test-00008-of-00010-d1aa19b51ad423d(…): reconstructing file:   0%|          |  0.00B /  409MB

data/test-00008-of-00010-d1aa19b51ad423d(…): downloading bytes:           |  0.00B

data/test-00009-of-00010-648ce5002d12449(…): reconstructing file:   0%|          |  0.00B /  299MB

data/test-00009-of-00010-648ce5002d12449(…): downloading bytes:           |  0.00B

Generating validation split:   0%|          | 0/9848 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/9289 [00:00<?, ? examples/s]

In [4]:
print(edacc)

DatasetDict({
    validation: Dataset({
        features: ['speaker', 'text', 'accent', 'raw_accent', 'gender', 'l1', 'audio'],
        num_rows: 9848
    })
    test: Dataset({
        features: ['speaker', 'text', 'accent', 'raw_accent', 'gender', 'l1', 'audio'],
        num_rows: 9289
    })
})

In [5]:
import pandas as pd

df = pd.DataFrame(
    edacc["validation"]
)

df.head()

,speaker,text,accent,raw_accent,gender,l1,audio
0,EDACC-C06-A,C ELEVEN DASH P ONE,Southern British English,English,male,Southern British English,<datasets.features._torchcodec.AudioDecoder ob...
1,EDACC-C06-B,C ELEVEN DASH P TWO,Mainstream US English,Trans-Atlantic,male,Mainstream US English,<datasets.features._torchcodec.AudioDecoder ob...
2,EDACC-C06-A,IGNORE_TIME_SEGMENT_IN_SCORING,Southern British English,English,male,Southern British English,<datasets.features._torchcodec.AudioDecoder ob...
3,EDACC-C06-B,IGNORE_TIME_SEGMENT_IN_SCORING,Mainstream US English,Trans-Atlantic,male,Mainstream US English,<datasets.features._torchcodec.AudioDecoder ob...
4,EDACC-C06-A,OKAY NOW FOR A REGULAR CONVERSATION SO UH WOUL...,Southern British English,English,male,Southern British English,<datasets.features._torchcodec.AudioDecoder ob...

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9848 entries, 0 to 9847
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   speaker     9848 non-null   object
 1   text        9848 non-null   object
 2   accent      9848 non-null   object
 3   raw_accent  9848 non-null   object
 4   gender      9848 non-null   object
 5   l1          9848 non-null   object
 6   audio       9848 non-null   object
dtypes: object(7)
memory usage: 538.7+ KB

In [8]:
df.isnull().sum()

speaker       0
text          0
accent        0
raw_accent    0
gender        0
l1            0
audio         0
dtype: int64